feat: INFRA-454 opter pour docker pour installer les dependances
Ferlab-Ste-Justine/openstack-bastion pull request #4
Opened 2023-08-04 13:27 UTC by ihannache

2023-08-04 20:41 UTC, sebastienbonami requested changes

2023-08-04 20:41 UTC, sebastienbonami commented on templates/cloud_config.yaml
The file `/opt/requirements.txt` can be removed (under `write_files`) as it's not used anymore.

2023-08-04 20:43 UTC, sebastienbonami commented
Also, not that it's important, but I would write the commit message in English (considering it's a public repo).

2023-08-04 20:59 UTC, sebastienbonami approved these changes, later dismissed

2023-08-07 14:34 UTC, Magnitus- submitted a review, later dismissed
LGTM

2023-08-12 03:14 UTC, merged